### PR TITLE
input: fix enabling/disabling single joycon mode on Switch

### PR DESCRIPTION
**Pull request by rsn8887**
Without this PR, Psnes, Pnes and Pfba all crash when switching single joycon mode from off to on.

### CODE REVIEW

**Comment by Cpasjuste** [comment]
Hi @rsn8887,

I am testing/implementing it directly in libcross2d. I wonder if the check "if (single_joy > 0)" is really needed as it seems to work fine in all modes (attached/detached) when it is set to 1/true ?

Also, i still have to make the "old workaround" to be able to press either start or select on detached/single joycon mode (use either select/start (+/-) + a normal button combo) which is not easy to understand for the end user. I wonder if it would be possible to hook the screenshot and home button to use them as either start/select.

**Comment by Cpasjuste** [comment]
It was added here: https://github.com/Cpasjuste/libcross2d/commit/75e86dbfabbf0e3381c4878d89437d7081104fd2

**Comment by rsn8887** [comment]
Awesome, yes in UAE I also handled plus and minus because left joycon only has minus, right only has plus. I used R3 i think (.push joy in) for the missing one. Or “hold L and press plus/minus” I forgot.

**Comment by Cpasjuste** [comment]
@rsn8887 , so you confirm i can use the code anytime, i can remove the "use single joycon" from the options menu(s)? 
Else, do you know/come on discord (Nintenbrew) ? Would be cool to talk sometime (i don't go on irc since we are on discord).

**Comment by rsn8887** [comment]
No you need the option menu, otherwise we always have to play multiplayer using mini joycons sideways. But many people have two big joycons, and want to use big joycons for two player, and single joycons only for four player. Heck, some people might have eight single joycons and want to play four player using four dual joycons (more comfortable to hold etc.)

It is much more comfortable to play two player using two dual big joycons, if you have four single ones and the holders to make two dual. Only if you don't have that many, you have to use the single mini joycons sideways. Which option to choose depends on how many Joycons you have.

Also in docked mode on TV, people of course want to use a dual joycon for single player, not have to use split joycon all the time!

So for sure we need the option in the menu!

**Comment by rsn8887** [comment]
Can you invite me to Nintenbrew? I am on Discord Henkaku etc.

**Comment by Cpasjuste** [comment]
Changes are finalized here, thanks :)
https://github.com/Cpasjuste/libcross2d/commit/fe5a384d487d7b600cf01563bb6765a27f313a1d

**Pull request closed without merging**
